# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "asynchro"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Tadman"]
  s.date = "2011-09-27"
  s.description = "Provides a number of tools to help make developing and testing asynchronous applications more manageable."
  s.email = "github@tadman.ca"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "asynchro.gemspec",
    "lib/asynchro.rb",
    "lib/asynchro/extensions.rb",
    "lib/asynchro/state.rb",
    "lib/asynchro/test_helper.rb",
    "lib/asynchro/tracker.rb",
    "test/helper.rb",
    "test/test_asynchro.rb",
    "test/test_asynchro_extensions.rb",
    "test/test_asynchro_state.rb",
    "test/test_asynchro_test_helper.rb",
    "test/test_asynchro_tracker.rb"
  ]
  s.homepage = "http://github.com/tadman/asynchro"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby EventMachine Async Programming Toolkit"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

